spring:
  #spring아래
  datasource:
    url: jdbc:h2:tcp://localhost/~/community
    username: sa
    password:
    driver-class-name: org.h2.Driver
  #spring아래
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #          show_sql: true
        format_sql: true


logging.level:
  org.hibernate.SQL: debug
#  org.hibernate:type: trace